const x = "{\r\n" + "    \"size\": 50000,\r\n" + "    \"query\": {\r\n"
+ "        \"bool\": {\r\n" + "            \"must\": [\r\n" + "                {\r\n"
+ "                    \"bool\": {\r\n" + "                        \"must\": [\r\n"
+ "                            {\r\n" + "                                \"terms\": {\r\n"
+ "                                    \"entity\": [" + "|top_entities_str|" + "],\r\n"
+ "                                    \"boost\": 1.0\r\n" + "                                }\r\n"
+ "                            },\r\n" + "                            {\r\n"
+ "                                \"terms\": {\r\n"
+ "                                    \"blogsite_id\": [" + "|blog_ids|" + "],\r\n"
+ "                                    \"boost\": 1.0\r\n" + "                                }\r\n"
+ "                            }\r\n" + "                        ],\r\n"
+ "                        \"adjust_pure_negative\": true,\r\n"
+ "                        \"boost\": 1.0\r\n" + "                    }\r\n" + "                },\r\n"
+ "                {\r\n" + "                    \"range\": {\r\n"
+ "                        \"date\": {\r\n" + "                            \"from\": \"" + "|date_from|"
+ "\",\r\n" + "                            \"to\": \"" + "|date_end|" + "\",\r\n"
+ "                            \"include_lower\": false,\r\n"
+ "                            \"include_upper\": false,\r\n"
+ "                            \"boost\": 1.0\r\n" + "                        }\r\n"
+ "                    }\r\n" + "                }\r\n" + "            ],\r\n"
+ "            \"adjust_pure_negative\": true,\r\n" + "            \"boost\": 1.0\r\n" + "        }\r\n"
+ "    },\r\n" + "    \"_source\": {\r\n" + "        \"includes\": [\r\n"
+ "            \"blogpost_id\",\r\n" + "            \"entity\",\r\n" + "            \"narrative\"\r\n"
+ "        ],\r\n" + "        \"excludes\": []\r\n" + "    },\r\n" + "    \"sort\": [\r\n"
+ "        {\r\n" + "            \"" + "|sort_field|" + "\": {\r\n" + "                \"order\": \""
+ "|sort_type|" + "\"\r\n" + " }\r\n" + "        }\r\n" + "    ]\r\n" + "}"


console.log(x);