export const headerData = [
    {
        "key": "id",
        "title": "S/N"
    },

    {
        "key": 0,
        "title": "Period"
    },
    {
        "key": 1,
        "title": "Data value"
    },
    {
        "key": 2,
        "title": "STATUS"
    },
    {
        "key": 3,
        "title": "UNITS"
    },
    {
        "key": 4,
        "title": "Subject"
    },
    {
        "key": 5,
        "title": "Group"
    },
    {
        "key": 6,
        "title": "Series title 1"
    },
    {
        "key": 7,
        "title": "Series title 2"
    },
    {
        "key": 8,
        "title": "Series title 3"
    },
    {
        "key": 9,
        "title": "Series title 4"
    },
    {
        "key": 10,
        "title": "Series title 5"
    }
]


export const initialData = [
    {
        "0": "CEPQ.S2371",
        "1": "1996.12,h",
        "2": "899",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1997.03",
        "2": "884",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1997.06",
        "2": "925",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1997.09",
        "2": "932",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1997.12",
        "2": "929",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1998.03",
        "2": "940",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1998.06",
        "2": "956",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1998.09",
        "2": "958",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1998.12",
        "2": "970",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1999.03",
        "2": "1000",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1999.06",
        "2": "1000",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1999.09",
        "2": "1000",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "1999.12",
        "2": "1000",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2000.03",
        "2": "949",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2000.06",
        "2": "953",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2000.09",
        "2": "964",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2000.12",
        "2": "970",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2001.03",
        "2": "970",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2001.06",
        "2": "936",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2001.09",
        "2": "936",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2001.12",
        "2": "961",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2002.03",
        "2": "962",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2002.06",
        "2": "928",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2002.09",
        "2": "928",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2002.12",
        "2": "965",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2003.03",
        "2": "969",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2003.06",
        "2": "970",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2003.09",
        "2": "970",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2003.12",
        "2": "970",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2004.03",
        "2": "970",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2004.06",
        "2": "970",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2004.09",
        "2": "972",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2004.12",
        "2": "952",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2005.03",
        "2": "955",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2005.06",
        "2": "955",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2005.09",
        "2": "931",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2005.12",
        "2": "931",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2006.03",
        "2": "980",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2006.06",
        "2": "969",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2006.09",
        "2": "969",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2006.12",
        "2": "1006",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2007.03",
        "2": "1007",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2007.06",
        "2": "1008",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2007.09",
        "2": "1142",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2007.12",
        "2": "1197",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2008.03",
        "2": "1056",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2008.06",
        "2": "1056",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2008.09",
        "2": "1056",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2008.12",
        "2": "1095",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2009.03",
        "2": "1124",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2009.06",
        "2": "1124",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2009.09",
        "2": "1120",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2009.12",
        "2": "1116",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    },
    {
        "0": "CEPQ.S2371",
        "1": "2010.03",
        "2": "1118",
        "3": "FINAL",
        "4": "Index",
        "5": "Capital Goods Price Index - CEP",
        "6": "Price Index by Item - Plant",
        "7": " Machinery and Equipment (Base: Sept 1999 = 1000)",
        "8": "Glass and glass products",
        "9": "",
        "10": "",
        "11": ""
    }
]